Default: COBBLESTONE

Chances:
  COAL_ORE: 3.0
  IRON_ORE: 2.5
  COPPER_ORE: 2.0
  LAPIS_ORE: 1.2
  REDSTONE_ORE: 1.2
  NETHERRACK: 1.2
  GOLD_ORE: 0.7
  DIAMOND_ORE: 0.5
  NETHER_QUARTZ_ORE: 0.5
  NETHER_GOLD_ORE: 0.5
  EMERALD_ORE: 0.4
  ANCIENT_DEBRIS: 0.1